spring.application.name=backend
server.port=${PORT}

client.url=${CLIENT_URL}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mvc.async.request-timeout=120000
spring.websocket.max-text-message-size=8192
spring.websocket.max-binary-message-size=65536
websocket.endpoint=/ws
websocket.allowed-origins=${CLIENT_URL}
spring.main.allow-circular-references=true
spring.task.scheduling.pool.size=5
server.tomcat.max-threads=200
server.tomcat.threads.max=200
spring.websocket.heartbeat.time=10000
spring.websocket.heartbeat.send-interval=25000
